      SUBROUTINE  WINDS (U,V,VEL,THETA,L)
C***********************************************************************
C*****WINDS TRANSFORMS FROM (U,V) TO (VEL,THETA) AND VICE VERSA
C-----SPECIFICATIONS
C*****THETA, MEASURED FROM NORTH CLOCKWISE, IS THE DIRECTION WIND COMES
C*****FROM. THETA IS RESTRICTED TO RANGE 0 TO 2*PI ON OUTPUT.
      DATA PI/3.1415926535897932D0/
      LOGICAL L
C     DOUBLE PRECISION SQRT
C     SQRT(DUMMY)=sqrt(DUMMY)
C     DOUBLE PRECISION SIN
C     SIN(DUMMY)=DSIN(DUMMY)
C     DOUBLE PRECISION COS
C     COS(DUMMY)=DCOS(DUMMY)
C     DOUBLE PRECISION DATAN2
C     ATAN2(DUMMY1,DUMMY2)=DATAN2(DUMMY1,DUMMY2)
C-----IF ( L ) TRANSFORM TO U AND V
      IF (L) GO TO 100
C-----(.NOT. L ) TRANSFORM TO VEL AND THETA
      VEL=SQRT(V*V+U*U)
      IF (VEL.LE.0) GO TO 50
      THETA=ATAN2(U,V) + PI
      RETURN
   50 THETA=0
      RETURN
C-----
  100 U=-VEL*SIN(THETA)
      V=-VEL*COS(THETA)
      RETURN
      END
